# Generated by Django 5.1.2 on 2025-01-19 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_remove_appointment_doctor_remove_appointment_patient_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='doctor_name',
            field=models.CharField(default='Unknown Doctor', max_length=255),
        ),
    ]
