# Generated by Django 5.1.2 on 2025-01-22 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_alter_user_date_of_birth_alter_user_last_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(blank=True, default='1000-01-01', null=True),
        ),
    ]
