# Generated by Django 5.1.2 on 2025-01-22 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_alter_user_date_of_birth'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='adress',
            new_name='address',
        ),
    ]
