# Generated by Django 5.1.2 on 2025-01-23 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_appointment_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='time',
        ),
    ]
