# Generated by Django 5.1.2 on 2025-01-24 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_alter_prescription_doctor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='doctor',
            field=models.CharField(max_length=100),
        ),
    ]
