# Generated by Django 5.1.2 on 2025-01-25 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_alter_appointment_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medication',
            old_name='name',
            new_name='medicine_name',
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('upcoming', 'Upcoming'), ('completed', 'Completed'), ('canceled', 'Canceled')], default='completed', max_length=10),
        ),
    ]
