# Generated by Django 5.1.2 on 2025-01-25 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_rename_name_medication_medicine_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='dosage',
            field=models.CharField(default='none', max_length=50),
        ),
        migrations.AddField(
            model_name='prescription',
            name='duration',
            field=models.CharField(default='none', max_length=50),
        ),
        migrations.AddField(
            model_name='prescription',
            name='frequency',
            field=models.CharField(default='none', max_length=50),
        ),
        migrations.AddField(
            model_name='prescription',
            name='medicine_name',
            field=models.CharField(default='none', max_length=100),
        ),
        migrations.DeleteModel(
            name='Medication',
        ),
    ]
