# Generated by Django 5.1.2 on 2025-01-25 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_prescription_dosage_prescription_duration_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescription',
            name='dosage',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='frequency',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='medicine_name',
        ),
        migrations.AddField(
            model_name='prescription',
            name='medicines',
            field=models.JSONField(default=list),
        ),
    ]
