# Generated by Django 5.1.2 on 2025-01-26 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_remove_prescription_dosage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('upcoming', 'Upcoming'), ('completed', 'Completed'), ('canceled', 'Canceled')], default='Null', max_length=10),
        ),
    ]
