# Generated by Django 5.1.2 on 2025-01-26 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_alter_appointment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='status',
            field=models.CharField(default='Pending', max_length=20),
        ),
    ]
